---
kind: pipeline
type: docker
name: default

platform:
    os: linux
    arch: arm

steps:
- name: get team data
  image: php:7.2
  commands:
    - php team.php js/data/team.json

- name: get player data
  image: php:7.2
  commands:
    - php biljartpoint.php js/data/team.json js/data/

- name: upload
  image: plugins/s3
  settings:
    bucket: carambolecomputer.nl
    region: eu-central-1
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: ./**/*
    target: /moyenne
    acl: public-read
    exclude:
      - .git/**/*
      - .*
